---
- name: Create a new database with name wikidatabase
  hosts: all
  remote_user: ansible-user
  become: yes
  tasks:
   - name: Set MySQL root Password
     mysql_user:
        login_user: 'root'
        login_password: ''
        name: 'root'
        password: '{{ mysql_root_pass }}'
        state: present
   - name: Create a new database with name wikidatabase
     mysql_db:
      name: wikidatabase
      state: present
      login_user: "root"
      login_password: '{{ mysql_root_pass }}'
   - name: Create user with password, all database privileges and WITH GRANT OPTION in wikidatabase
     mysql_user:
      state: present
      name: wiki
      password: '{{ wiki_pass }}'
      login_user: "root"
      login_password: '{{ mysql_root_pass }}'
      priv:
        'wikidatabase.*': 'ALL,GRANT'
   - name: Removing all anonymous user accounts
     mysql_user:
      name: ''
      host_all: yes
      state: absent
      login_user: "root"
      login_password: '{{ mysql_root_pass }}'      
   - name: Delete all the test databases.
     mysql_db:
      name: test
      state: absent
      login_user: "root"
      login_password: '{{ mysql_root_pass }}'